# Describes the format for available hue services

# legacy hue_activate_scene to activate a scene
hue_activate_scene:
  fields:
    group_name:
      example: "Living Room"
      selector:
        text:
    scene_name:
      example: "Energize"
      selector:
        text:
    dynamic:
      selector:
        boolean:

# entity service to start/stop a native signaling effect on lights (V2)
signal:
  target:
    entity:
      domain: light
      integration: hue
  fields:
    signal:
      required: true
      example: "on_off_color"
      selector:
        select:
          options:
            - "no_signal"
            - "on_off"
            - "on_off_color"
            - "alternating"
          translation_key: signal_type
    duration:
      example: 30
      selector:
        number:
          min: 1
          max: 65534
          unit_of_measurement: seconds
    color:
      example: "[255, 165, 0]"
      selector:
        color_rgb:
    color2:
      selector:
        color_rgb:

# entity service to activate a Hue scene (V2)
activate_scene:
  target:
    entity:
      domain: scene
      integration: hue
  fields:
    transition:
      selector:
        number:
          min: 0
          max: 3600
          unit_of_measurement: seconds
    dynamic:
      selector:
        boolean:
    scene_customization:
      collapsed: true
      fields:
        speed:
          selector:
            number:
              min: 0
              max: 100
        brightness:
          selector:
            number:
              min: 1
              max: 255
